"""add_integrity_constraints_and_indices

Revision ID: 5ef5c43b7e72
Revises: 9d6c3d6f6cfc
Create Date: 2026-10-04 00:07:48.584752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef5c43b7e72'
down_revision: Union[str, Sequence[str], None] = '9d6c3d6f6cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_applications_user_job', 'applications', ['user_id', 'job_id'])
    op.create_unique_constraint('uq_job_skills_job_skill', 'job_skills', ['job_id', 'skill_id'])
    op.create_index('ix_jobs_source_source_url', 'jobs', ['source', 'source_url'], unique=False)
    op.create_unique_constraint('uq_saved_jobs_user_job', 'saved_jobs', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_jobs_user_job', 'saved_jobs', type_='unique')
    op.drop_index('ix_jobs_source_source_url', table_name='jobs')
    op.drop_constraint('uq_job_skills_job_skill', 'job_skills', type_='unique')
    op.drop_constraint('uq_applications_user_job', 'applications', type_='unique')
    # ### end Alembic commands ###
