"""add job analysis status

Revision ID: c99324f3bf8c
Revises: adbd1a348156
Create Date: 2026-09-08 20:53:16.385243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99324f3bf8c'
down_revision: Union[str, Sequence[str], None] = 'adbd1a348156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "jobs",
        sa.Column(
            "analysis_status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'analysis_status')
    # ### end Alembic commands ###
